### PR TITLE
- Hide header on to narrow displays, because it overlap the controls

### PR DESCRIPTION
**Pull request by GermanBluefox**
- Add lazy load of the states for ioBroker

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Ping?

**Comment by Apollon77** [comment]
The TileBoard UI is great, I would be happy to see support also for ther smart home systems like ioBroker.
@resoai What do you think? Do you need changes here then please give feedback ...

To join forces especially for UI topics is a great advantage for open source projects

**Comment by resoai** [comment]
Sorry guys, I was travelling with little to no access to the internet. I feel that the correct way would still be to fork the project and do native calls to iobroker rather than trying to map the calls. There is very little still planned to be implemented in TileBoard so syncing any changes would not be too hard. 

There is also a matter of personal opinion which could further slow down the development.

**Comment by GermanBluefox** [comment]
Жаль

**Pull request closed without merging**
