### PR TITLE
Add support for armed_night state

### PR DESCRIPTION
**Pull request by Juggels**
Home Assistant supports the `armed_night` state. This PR adds support for this state to the Alarm card.

### CODE REVIEW

**Comment by Evgeny-** [comment]
We had troubles with .includes, #63 people use tileboard on IE. I think will be better create separate function in main controller (something like `isDisarmed`?) and use .indexOf instead.

**Comment by resoai** [comment]
Isn't armed_home identical to armed_night ?

**Comment by Juggels** [comment]
> We had troubles with .includes, #63 people use tileboard on IE. I think will be better create separate function in main controller (something like `isDisarmed`?) and use .indexOf instead.

Good one, I did not think to check that. I will refactor accordingly.

**Comment by Juggels** [comment]
> Isn't armed_home identical to armed_night ?

That depends I guess... They are implemented separately in Home Assistant. For my personal use case, they differ in use as well: `armed_home` is used for an extra sense/layer of security when someone is home alone, whereas `armed_night` is used (as the name suspects) to trigger on some other stuff as well during the night time.

**Comment by Evgeny-** [comment]
@Juggels thank you. I've moved changes from .css file to .less (we use .less for developing, .css is basically translation)

**Pull request merged**
