### PR TITLE
Improving the media_player with source selecting

### PR DESCRIPTION
**Pull request by fortminor0692**
Uncommenting the source selection part and automatically select the active source playing. (tile.html)
Tweaking the css so all the div's fit into a tile of 2 x 1, mostly by putting the prev and next button beside the mute button. (main.css)
Adding the logic for changing the source. (main-controller.js)

### CODE REVIEW

**Comment by fortminor0692** [comment]
The players look like this now.  (There are two in the screenshot) 
afbeelding

**Comment by Evgeny-** [comment]
Hey, thanks for commit! I've edited few things of this pull: code formatting, place of the source button and put changes into .less file (instead of .css)

**Comment by resoai** [comment]
It is really nice to see people getting on board! Let's keep it up!

**Comment by Evgeny-** [comment]
Not sure why git think i've not merged this pull request tho

**Pull request closed without merging**
