### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by jschwalbe**
Make the config.js load freshly with each refresh by appending the date to the end of config.js (so one doesn't have to clear cache or force reload each time!).

Tested in Apache & Homeassistant (on macOS)

### CODE REVIEW

**Comment by avishayil** [comment]
I think this could be good only for development, while in production you'll probably want browser cache active.

**Comment by resoai** [comment]
Yes, and to be frank in most browsers there is a way to not cache the resource.

**Comment by jschwalbe** [comment]
@resonai @avishayil Hm I respectfully disagree. What is the harm in reloading it each time? Especially when there's so many people trying to figure out why changes don't show up after editing the config.js file?

**Comment by avishayil** [comment]
@jschwalbe Because you're probably running on Raspberry Pi where you want to preserve computing resources. Developers can disable cache on development machines.

**Comment by resoai** [comment]
Embedding javascript files via `document.write` is simply incorrect and causes even more problems. In fact all you need to do is tick one box when you edit the file.

photo_2018-09-28_11-34-24

**Pull request closed without merging**
