### PR TITLE
fix: enable arm buttons based on supported alarm features

### LINKED ISSUE #365: Customize alarm action selection
My alarm system does not have an "Alarm Night" style behavior (to the best of my knowledge). Would be good to choose which actions are available to support various configurations.

### PR DESCRIPTION
**Pull request by rchl**
Resolves #365

### CODE REVIEW

**Comment by rchl** [comment]
@akloeckner Care to review?

**Comment by akloeckner** [comment]
Sure! I'll be able to test earliest Thursday, though...

**Review by akloeckner — APPROVED** [review]
Actually, my `manual` alarm panel supports all those features. So, not much to test in the end. Looks good! 

If we were to clean up while passing by, I'd fix up the `isDisarmed` function to simply
```
return entity.state != 'disarmed';
```

**Comment by rchl** [comment]
Removed `isDisarmed`. It doesn't add much and I would prefer to have as few scope methods as possible.

**Comment by akloeckner** [comment]
:+1: My parameter for a good PR also is "more lines removed than added". ;-)

Just a logical twist, that strikes my mind: Is it really correct to enable the `arm` actions only, if the alarm is already `armed`. (And vice versa.) It seems to work correctly, but I don't understand, why...

**Comment by rchl** [comment]
No, you are right. It's backwards and doesn't work as intended. Will fix.

**Review by akloeckner — APPROVED** [review]
I hope you weren't waiting for my approval...

**Comment by rchl** [comment]
Was planning to merge eventually but was not in a rush. :)

**Pull request merged**
