### PR TITLE
feat: make tileboard installable as web apk

### LINKED ISSUE #819: Samsung phones: Progressive Web App lacks service worker
I wondered why TileBoard wouldn't install as a PWA on my new samsung phone. It appears,  we would need a (at least) dummy service worker installed. 

Here's a list of requirements: https://superpwa.com/doc/test-pwa-samsung-internet-browser/

### PR DESCRIPTION
**Pull request by akloeckner**
fixes #819

This
* adds a dummy service worker with a fetch handler
* increases the favicon size to 512px and adds a vector source graphic
* adds a start_url to the webmanifest

The service worker's scope is automatically just the path to its js file. (See [Google's primer on it](https://developers.google.com/web/fundamentals/primers/service-workers#register_a_service_worker).)

The ingress mode of the addon can disable the service worker via `window.IN_INGRESS = true`. See PR there: https://github.com/resoai/TileBoard-addon/pull/32.

### CODE REVIEW

**Comment by rchl** [comment]
FYI: I've acknowledged this PR but didn't have time to look into it yet.

**Comment by akloeckner** [comment]
Thanks for the feedback! We're in no hurry, things are working swiftly already: I have just kept my once installed app from my test branch. ;-)

**Comment by rchl** [comment]
Made minor changes:
 - optimized SVG
 - small style changes

**Comment by akloeckner** [comment]
The manifest changes haven't made it to the PR yet.

**Review by rchl — APPROVED** [review]

**Comment by akloeckner** [comment]
Yeay! Thanks.

I believe `start_url` is a requirement, though. I just did a quick test on my mobile and didn't get the "install" option. I'll check again on a laptop as soon as I find time.

**Comment by rchl** [comment]
I've misinterpreted my local changes after all this time and thought that this was something that I've added when experimenting...
Should definitively restore it then.

**Pull request merged**
