### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by gerard33**
The html page was missing a favicon, so adding one from https://materialdesignicons.com.

### CODE REVIEW

**Comment by gerard33** [comment]
I just took this dashboard icon https://materialdesignicons.com/icon/view-dashboard.
But of course another icon is fine as well, just missing one in the current page.

**Comment by resoai** [comment]
If I remember correctly, in order to make it correctly, there must be about 10 different sizes for iOS and about 5 for Android :) I'd love to have something unique for the icon, so let's get back to this one.

**Comment by gerard33** [comment]
Maybe this link is helpful https://gist.github.com/ianaya89/45731a1ab52a9fb6e7d9.
Now to find a nice icon :grinning:

**Comment by resoai** [comment]
Thanks, I have that list. The problem is to come up with a decent icon which is proving to be difficult.

**Comment by Evgeny-** [comment]
Ok, i've added some favicon. Probably it isn't perfect, but unless some one shows something better it will be like that.

**Pull request closed without merging**
