### PR TITLE
Added RGB Color picker

### PR DESCRIPTION
**Pull request by danhounshell**
Added RGB Color picker since it is a popular request: #128 

Based on: https://github.com/Alberplz/angular-colorpicker-directive with a few slight modifications to get it working well with TileBoard (I probably ought to fork that repo and keep track of the changes that I made)

Color picker is available on the 2nd view of light tile if the entity has an `rgb_color` attribute.

Only the RGB properties are sent to HA, the Alpha property, if set, is discarded.

Screenshot of it in action:

RGBColorPickerTileBoard

### CODE REVIEW

**Comment by danhounshell** [comment]
Could probably use a little more tweaking to get rid of the alpha controls altogether but I ran out of time for the day and I wanted to get this posted before I got sidetracked onto something else.

**Comment by danhounshell** [comment]
Commented out some of the functionality from color-picker that we are not using. Now looks like this:

RGBColorPickerTileBoard_2

**Comment by resoai** [comment]
Thank you for your effort! I'm sure a lot of users will appreciate it. 

Perhaps if you will have some free time in future it would be nice to get rid of "R" "G" and "B" if you are considering forking it and styling cancel button.

**Comment by Evgeny-** [comment]
Thank you for commit. Please in the next time respect our code style, and don't forget that we use es4

**Comment by danhounshell** [comment]
@Evgeny- I saw your follow up commit and noted the things you updated. Thank you.

**Pull request merged**
