### PR TITLE
fix: use polyfill for URLSearchParams

### PR DESCRIPTION
**Pull request by akloeckner**
since it is not available on iOS 9.3.5 (i.e. old iPads e.g.)

see #530, @anthony2856

### CODE REVIEW

**Comment by rchl** [comment]
Can you try this instead: https://github.com/resoai/TileBoard/pull/557 ?

I haven't tried it on a device that doesn't support URLSearchParams but looking at the generated code, it looks like something like a polyfill is added.

Please try first without switching to `URLSearchParams` to check if the URL.searchParams is pollyfilled.
If that doesn't work, please try switching to explicit `URLSearchParams`.

**Comment by rchl** [comment]
And the motivation for doing the way I did it is that it's better to handle this transparently through babel than explicitly through a third-party package.

**Comment by akloeckner** [comment]
I see the advantage. But I can't test it. I get an `undefined` error. I get the same from `master`, actually...

**Comment by rchl** [comment]
Not sure where you getting this `undefined` exactly but maybe try adding this and see if the tablet shows more meaningful error:

```diff
--- a/scripts/globals.js
+++ b/scripts/globals.js
@@ -26,6 +26,8 @@ window.onerror = function (error, file, line, char) {
       'Line: ' + line + ':' + char,
    ].join('<br>');
 
+   alert(text);
+
    Noty.addObject({
       type: Noty.ERROR,
       title: 'JS error',
```

**Comment by rchl** [comment]
I've added an extra commit that fixes notifications not working when there is a syntax error in the config. This should ensure that the user will be able to see where the actual error is.

**Comment by rchl** [comment]
And BTW, I also have an old iPad with iOS 9 and I was able to verify that this fixes the issue. But I'd like you to confirm that also. :)

**Comment by akloeckner** [comment]
It's not on the tablet, but on my desktop Firefox. I get this:
grafik

From master. 2f9cee8 is still ok.

**Comment by rchl** [comment]
With `yarn dev` or `yarn build`?

**Comment by akloeckner** [comment]
yarn build

**Comment by rchl** [comment]
Did you make sure to run `yarn` first to install the new dependency.

**Comment by akloeckner** [comment]
tried now to run `yarn`. it says already up-to-date. Ill runn build again. I'll be back in 3 mins...

**Comment by akloeckner** [comment]
still the same. but since you oviously don't have that... I'll check if there's something offending in my config...

**Comment by rchl** [comment]
Yeah, I don't see that with my config. Neither on Firefox nor Chrome.
You could check with the example config to see if it just loads.
Also, is `yarn dev` working? It should provide a better error message if it also reproduces.

**Comment by akloeckner** [comment]
It's ok with the example configuration. 

With my actual configuration, `yarn dev` also fails. `too much recursion` is what the error seems to be:
grafik

I'm stuck for now... I might find out more in the next days... :-/

**Comment by akloeckner** [comment]
Got it. I have that in my `TILE_DEFAULTS`:
```
   [TYPES.CAMERA]: {
      // Have fullscreen
      fullscreen: {
         type: TYPES.CAMERA,
         //bgSize: 'contain',
      }
   }
```

I'll probably open an issue on it, when I still consider that to be allowable tomorrow morning. :-)

**Comment by rchl** [comment]
Interesting case.

It feels a bit wrong to specify the defaults for two different tiles at once.

But it might make sense for cases when we want to provide different defaults for a given tile, depending on where it's used.

We still have to recursively merge in some cases, like when the user provides a `popup` object for the POPUP tile, for example.

**Comment by rchl** [comment]
I've merged my change after confirming that it's working on iOS 9.

**Pull request closed without merging**
