### PR TITLE
feat: allow custom classes on screensaver slides

### PR DESCRIPTION
**Pull request by rsmhass**

### CODE REVIEW

**Comment by rchl** [comment]
Should be also mentioned in the readme. Otherwise it's a feature that nobody will know about.

**Comment by rsmhass** [comment]
> Should be also mentioned in the readme. Otherwise it's a feature that nobody will know about.

I was thinking of updating https://github.com/resoai/TileBoard/wiki/Screensaver-configuration rather than updating the README.md. README has lesser of screensaver details than the wiki page. If I update the README with just this feature, then that would be off.

I am assuming I would have the permission to edit https://github.com/resoai/TileBoard/wiki/Screensaver-configuration

**Comment by rchl** [comment]
Yes, readme should regardless list all supported options, even if it does not go into details.

**Comment by rsmjs** [comment]
@rchl I have added documentation for the feature to README. Can this be merged now ?

**Comment by rsmhass** [comment]
@rchl I have added documentation for the feature to README. Can this be merged now ?

**Pull request merged**
