### PR TITLE
Enable/Disable Swipe

### PR DESCRIPTION
**Pull request by obimichael**
Implemented to turn of swipe in config. If attribute swipeEnabled is missing in config, swipeEnabled = true.

### CODE REVIEW

**Comment by resoai** [comment]
In such a case, this should probably be disableSwipe and you need to use “===“ operator to avoid type conversion and there is no need to check for null.

**Comment by obimichael** [comment]
First of all sorry for the many commits, my first time on github. ;-)
You're right and I changed the operator, but I would leave "enabled" in the parameter name, because of the other parameter wording

**Comment by rchl** [comment]
I wonder if it should have more explicit naming. `enableSwipe` refers to swiping action and not to the feature that it enables/disables. I think it's a bit too low-level. In a hypothetical situation where we would use swipe for more actions, would we want those to also be disabled? I think potentially not. So I think better naming could be `disablePageToggleWithSwipe`.

**Comment by rchl** [comment]
Also, any particular reason for disabling it?
If it conflicts with some workflow of yours, maybe that could be improved/fixed instead?
Adding options adds complexity and potential for bugs in the feature.

**Comment by akloeckner** [comment]
Maybe this is the reason? 

https://community.home-assistant.io/t/tileboard-new-dashboard-for-homeassistant/57173/2702

**Comment by rchl** [comment]
I saw that but then it would make sense to either fix that or exclude older safari versions automatically.

**Comment by akloeckner** [comment]
Oh no, please let's not do that. I'm very happy that things just work on my stone age iPad...

**Comment by rchl** [comment]
By excluding I meant to disable the feature that causes the problem. In this case swiping to toggle pages. :)

**Comment by akloeckner** [comment]
Ouff. ;-) 

Btw. The post in the forums is with respect to an iPhone on iOS 13.x. So, it's not an old version.

**Comment by resoai** [comment]
> 
> 
> Maybe this is the reason?
> 
> https://community.home-assistant.io/t/tileboard-new-dashboard-for-homeassistant/57173/2702

I think that this was my worry when we introduced `Hammer.js`.

**Comment by rchl** [comment]
> I think that this was my worry when we introduced Hammer.js.

I'll have a look when I have some time.

But I'm not sure what you mean by "this" in "this was my worry" :)
The issue is not necessarily with the hammer library itself. It could be that we are not preventing some event. Or could be that just having a touch handler higher in the three conflicts with native range handler, irrespective of the library type.

**Comment by resoai** [comment]
I mean that I tried adding swipe gestures at the very beginning and faced some issues with other controls, so I decided to abandon the idea :)

**Comment by rchl** [comment]
Created #302 to fix issues with sliders.

**Comment by resoai** [comment]
@obimichael belive we can close this one now?

**Comment by obimichael** [comment]
okay

**Pull request closed without merging**
