### PR TITLE
Added optional date to header

### PR DESCRIPTION
**Pull request by NilSkilz**
I've added the date to my header, which is controlled by an optional parameter in the config JSON. 

I felt like you may have had plans for this yourself? based on the clockStyles() function? Anyway it could probably be expanded to allow for right aligned clocks/dates etc. It would be cool to know if you had any plans yourself.

### CODE REVIEW

**Comment by Evgeny-** [comment]
Just do not include header in the page

**Comment by NilSkilz** [comment]
I'm confused by this comment. How does that achieve the objective of having the date and time on the screen?

**Comment by Evgeny-** [comment]
Oh. i see you did opposite. My mistake, sorry. 

We should work on header, may be will be better open an issue.

**Comment by Evgeny-** [comment]
Here it is https://github.com/resoai/TileBoard/issues/92

**Pull request closed without merging**
